export default interface ParamsModel {
  vendaBloqueada?: boolean,
  urlLiveStream?: string,
  regulamento?: string,
  mensagemPremios?: string,
  banner?: string,
  baseComissaoGerente: 0,
  baseComissaoVendedor: 0,
  valorCartelaAtual: number,
  dataDoSorteio?: Date,
  gerentesDoGiro?: [],
  valorLinha: 0,
  valorColuna: 0,
  valorCruz: 0,
  valorCantos: 0,
  valorCheia: 0,
  valorL: 0,
  valorX: 0,
  valorJanelinha: 0,
  valorJanelao: 0,
  valorGiro: 0,
  valorSuperGiro: 0,
  raffleNumbers?: []
  }